export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_TRACK_NUMBERS_LOADING = 'GET_TRACK_NUMBERS_LOADING';
export const GET_TRACK_NUMBERS_SUCCESS = 'GET_TRACK_NUMBERS_SUCCESS';
export const GET_TRACK_NUMBERS_FAIL = 'GET_TRACK_NUMBERS_FAIL';

export const CREATE_TRACK_NUMBER_LOADING = 'CREATE_TRACK_NUMBER_LOADING';
export const CREATE_TRACK_NUMBER_SUCCESS = 'CREATE_TRACK_NUMBER_SUCCESS';
export const CREATE_TRACK_NUMBER_FAIL = 'CREATE_TRACK_NUMBER_FAIL';

export const DELETE_TRACK_NUMBER_LOADING = 'DELETE_TRACK_NUMBER_LOADING';
export const DELETE_TRACK_NUMBER_SUCCESS = 'DELETE_TRACK_NUMBER_SUCCESS';
export const DELETE_TRACK_NUMBER_FAIL = 'DELETE_TRACK_NUMBER_FAIL';

export const EDIT_TRACK_NUMBER_LOADING = 'EDIT_TRACK_NUMBER_LOADING';
export const EDIT_TRACK_NUMBER_SUCCESS = 'EDIT_TRACK_NUMBER_SUCCESS';
export const EDIT_TRACK_NUMBER_FAIL = 'EDIT_TRACK_NUMBER_FAIL';
